//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosSistema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosSistema() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppDigitalCv.Recursos.RecursosSistema", typeof(RecursosSistema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ~/Imagenes/Usuarios/.
        /// </summary>
        internal static string DOCUMENTO_USUARIO {
            get {
                return ResourceManager.GetString("DOCUMENTO_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string FAMILIAR_HIJO {
            get {
                return ResourceManager.GetString("FAMILIAR_HIJO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3.
        /// </summary>
        internal static string FAMILIAR_MADRE {
            get {
                return ResourceManager.GetString("FAMILIAR_MADRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2.
        /// </summary>
        internal static string FAMILIAR_PADRE {
            get {
                return ResourceManager.GetString("FAMILIAR_PADRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4.
        /// </summary>
        internal static string FAMILIAR_PAREJA {
            get {
                return ResourceManager.GetString("FAMILIAR_PAREJA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el Nombre..
        /// </summary>
        internal static string INGRESAR_NOMBRE {
            get {
                return ResourceManager.GetString("INGRESAR_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagenes/Usuarios/.
        /// </summary>
        internal static string URL_PERFIL {
            get {
                return ResourceManager.GetString("URL_PERFIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Usuario No Existe..
        /// </summary>
        internal static string USUARIO_INEXISTENTE {
            get {
                return ResourceManager.GetString("USUARIO_INEXISTENTE", resourceCulture);
            }
        }
    }
}
