//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catDireccion
    {
        public int idDireccion { get; set; }
        public string strCalle { get; set; }
        public string strNumeroInterior { get; set; }
        public string strNumeroExterior { get; set; }
        public int idColonia { get; set; }
        public Nullable<bool> bitActual { get; set; }
        public Nullable<int> idPersonal { get; set; }
    
        public virtual CatColonia CatColonia { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
