//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatEnfermedadesExantemática
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatEnfermedadesExantemática()
        {
            this.CatRespuestas07 = new HashSet<CatRespuestas07>();
        }
    
        public int id { get; set; }
        public Nullable<bool> Varicela { get; set; }
        public Nullable<bool> Rubeola { get; set; }
        public Nullable<bool> Sarampión { get; set; }
        public Nullable<bool> Escarlatina { get; set; }
        public Nullable<bool> Exantema_Súbito { get; set; }
        public Nullable<bool> Enfermedad_de_Manos__Pies__Boca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatRespuestas07> CatRespuestas07 { get; set; }
    }
}
