//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catFamiliar
    {
        public int idFamiliar { get; set; }
        public string strNombre { get; set; }
        public string strApellidoPaterno { get; set; }
        public string strApellidoMaterno { get; set; }
        public string strOcupacion { get; set; }
        public string strDomicilio { get; set; }
        public Nullable<bool> bitVive { get; set; }
        public Nullable<System.DateTime> dteFechaNacimiento { get; set; }
        public Nullable<int> idParentesco { get; set; }
        public Nullable<int> idPersonal { get; set; }
    
        public virtual catParentesco catParentesco { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
