//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatRespuestas05
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatRespuestas05()
        {
            this.TblEncuesta = new HashSet<TblEncuesta>();
        }
    
        public int id { get; set; }
        public Nullable<int> idRh { get; set; }
        public Nullable<int> idGrupoSanguineo { get; set; }
    
        public virtual CatGrupoSanguineo CatGrupoSanguineo { get; set; }
        public virtual CatRH CatRH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblEncuesta> TblEncuesta { get; set; }
    }
}
