//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCapituloLibro
    {
        public int id { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public Nullable<int> idStatus { get; set; }
        public string strAutor { get; set; }
        public string strTitulo { get; set; }
        public Nullable<int> enumEstadoActual { get; set; }
        public Nullable<int> idPais { get; set; }
        public string strEditorial { get; set; }
        public string strEdicion { get; set; }
        public Nullable<System.DateTime> dteFechaPublicacion { get; set; }
        public string strTiraje { get; set; }
        public string strISBN { get; set; }
        public string enumProposito { get; set; }
        public string strTituloCapitulo { get; set; }
        public string strAutores { get; set; }
        public Nullable<int> paginaInicio { get; set; }
        public Nullable<int> paginaTermino { get; set; }
        public Nullable<bool> bitLigarCurriculum { get; set; }
    
        public virtual catStatus catStatus { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
