//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCapacitacionesImpartidas
    {
        public int id { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> idTipoCapacitacion { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public string strNombre { get; set; }
        public string strLugarIntitucion { get; set; }
        public string strTotalHoras { get; set; }
        public Nullable<System.DateTime> dteFecha { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual CatTiposCapacitacion CatTiposCapacitacion { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
