//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;

    public partial class TblDocumentosProfesionales
    {
        public int id { get; set; }
        public string strNombre { get; set; }
        public Nullable<int> idDoctorado { get; set; }
        public Nullable<int> idMaestria { get; set; }
        public Nullable<int> idLicenciaturaIng { get; set; }
        public Nullable<int> idBachillerato { get; set; }

        public virtual TblDoctorado TblDoctorado { get; set; }
        public virtual TblLicenciaturaIngenieria TblLicenciaturaIngenieria { get; set; }
        public virtual TblMaetria TblMaetria { get; set; }
        public virtual TblBachillerato TblBachillerato { get; set; }
    }
}
