//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDoctorado
    {
        public int id { get; set; }
        public string strNombre { get; set; }
        public Nullable<int> idInstitucionAcreditaDoctorado { get; set; }
        public Nullable<int> idStatusDoctorado { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> idFuenteFinanciamientoDoctorado { get; set; }
        public Nullable<bool> bitReconomientoPNPC { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public Nullable<System.DateTime> dteFechaInicio { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual CatFuenteFinanciamientoDoctorado CatFuenteFinanciamientoDoctorado { get; set; }
        public virtual CatInstitucionAcreditaDoctorado CatInstitucionAcreditaDoctorado { get; set; }
        public virtual CatStatusDoctorado CatStatusDoctorado { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
