//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExperienciaLaboralExterna
    {
        public int id { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> idTipoPersonal { get; set; }
        public string strInstitucionEmpresa { get; set; }
        public string strPeriodo { get; set; }
        public string dteFechaInicio { get; set; }
        public string dteFechaFinal { get; set; }
        public string strActividades { get; set; }
        public string strMotivoConclucion { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
