//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstadiaEmpresa
    {
        public int id { get; set; }
        public Nullable<int> idProgramaEducativo { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public string strNombreAlumno { get; set; }
        public string strResumenProyecto { get; set; }
        public string strObjetivo { get; set; }
        public string dteFechaInicio { get; set; }
        public string dteFechaTermino { get; set; }
        public string strNombreEmpresaInstitucion { get; set; }
        public string strPuntosCriticosResolver { get; set; }
        public string strLogrosBeneficiosObtenidos { get; set; }
        public string strEstadoEstadia { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual catProgramaEducativo catProgramaEducativo { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
