//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExperienciaLaboralInterna
    {
        public int id { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public Nullable<int> idArea { get; set; }
        public Nullable<int> idProgramaEduactivo { get; set; }
        public string dteFechaInicio { get; set; }
        public string dteFechaFin { get; set; }
        public string strActividadDesempenada { get; set; }
        public string strTipoProfesor { get; set; }
    
        public virtual catArea catArea { get; set; }
        public virtual catProgramaEducativo catProgramaEducativo { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
