//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblIdioma
    {
        public int id { get; set; }
        public Nullable<int> idIdioma { get; set; }
        public Nullable<int> idNivelConocimiento { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> idPersonal { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual catIdioma catIdioma { get; set; }
        public virtual CatNivelConocimiento CatNivelConocimiento { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
