//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLenguas
    {
        public int id { get; set; }
        public Nullable<int> idLengua { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public string strEscritura { get; set; }
        public string strLectura { get; set; }
        public string strEntendimiento { get; set; }
        public string strComunicacion { get; set; }
    
        public virtual CatLenguas CatLenguas { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
