//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLibro
    {
        public int id { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public Nullable<int> idPais { get; set; }
        public string strAutores { get; set; }
        public string strTituloLibro { get; set; }
        public string strTipoParticipacion { get; set; }
        public string strEstadoActual { get; set; }
        public string strEditorial { get; set; }
        public Nullable<int> Paginas { get; set; }
        public string strEdicion { get; set; }
        public string strTiraje { get; set; }
        public string strISBN { get; set; }
        public string FechaPublicacion { get; set; }
        public string strProposito { get; set; }
    
        public virtual CatPais CatPais { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
