//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMaetria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMaetria()
        {
            this.TblDocumentosProfesionales = new HashSet<TblDocumentosProfesionales>();
        }
    
        public int id { get; set; }
        public string strNombre { get; set; }
        public Nullable<int> idInstitucionAcreditaMaestria { get; set; }
        public Nullable<int> idStatusMaestria { get; set; }
        public Nullable<int> idFuentaFinanciamientoMaestria { get; set; }
        public Nullable<bool> bitReconocidoPNPC { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public string dteFechaInicio { get; set; }
    
        public virtual CatFuentaFinaciamientoMaestria CatFuentaFinaciamientoMaestria { get; set; }
        public virtual CatInstitucionAcreditaMaestria CatInstitucionAcreditaMaestria { get; set; }
        public virtual CatStatusMaestria CatStatusMaestria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDocumentosProfesionales> TblDocumentosProfesionales { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
