//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOtraCapacitacion
    {
        public int id { get; set; }
        public Nullable<int> idCapacitacionRecibida { get; set; }
        public string strNombreDiplomadoCursoTaller { get; set; }
        public string strNumeroHoras { get; set; }
        public Nullable<int> idIOtranstitucionAcredita { get; set; }
        public Nullable<int> idPersonal { get; set; }
    
        public virtual CatCapacitacionesCompetenciasProfesionales CatCapacitacionesCompetenciasProfesionales { get; set; }
        public virtual CatIntitucionAcreditaOtra CatIntitucionAcreditaOtra { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
