//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrototipo
    {
        public int id { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public string strAutor { get; set; }
        public string strTipoPrototipo { get; set; }
        public string strNombrePrototipo { get; set; }
        public string strObjetivos { get; set; }
        public string strCaracteristicas { get; set; }
        public string strInstitucionDestinada { get; set; }
        public string dteFechaPublicacion { get; set; }
        public string strEstadoActual { get; set; }
        public string strProposito { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual CatPais CatPais { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
