//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParticipacionDocente
    {
        public int id { get; set; }
        public Nullable<int> idCatDocumento { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public string strEvento { get; set; }
        public string strTipoEvento { get; set; }
        public string strParticipacion { get; set; }
        public string strTipoParticipacion { get; set; }
        public Nullable<bool> bitPonencia { get; set; }
        public string strNombrePonencia { get; set; }
        public string strNombreInstitucionEmpresa { get; set; }
        public string strLugar { get; set; }
        public Nullable<System.DateTime> dteFecha { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
