//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTutoria
    {
        public int id { get; set; }
        public Nullable<int> idPersonal { get; set; }
        public Nullable<int> idProgramaEductivo { get; set; }
        public string strNombreEstudiante { get; set; }
        public Nullable<System.DateTime> dteFechaInicio { get; set; }
        public Nullable<System.DateTime> dteFechaTermino { get; set; }
        public string strEstadoTutoria { get; set; }
        public string strHoras { get; set; }
        public string strTipo { get; set; }
    
        public virtual catProgramaEducativo catProgramaEducativo { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
