//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUsuario()
        {
            this.administrar = new HashSet<administrar>();
            this.TblFavoritos = new HashSet<TblFavoritos>();
        }
    
        public int IdUsuario { get; set; }
        public string strUsuario { get; set; }
        public string Email { get; set; }
        public string Contraseña { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string strNombre { get; set; }
        public string strApellidoP { get; set; }
        public string strApellidoM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<administrar> administrar { get; set; }
        public virtual catCategoria catCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblFavoritos> TblFavoritos { get; set; }
    }
}
