//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDigitalCv.Business.ServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seguridad", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Seguridad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegUsuario {
            get {
                return this.SegUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.SegUsuarioField, value) != true)) {
                    this.SegUsuarioField = value;
                    this.RaisePropertyChanged("SegUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SegPassword {
            get {
                return this.SegPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.SegPasswordField, value) != true)) {
                    this.SegPasswordField = value;
                    this.RaisePropertyChanged("SegPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomUsuario {
            get {
                return this.NomUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomUsuarioField, value) != true)) {
                    this.NomUsuarioField = value;
                    this.RaisePropertyChanged("NomUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private AppDigitalCv.Business.ServiceClient.EnumCodigosError CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private bool AccesoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Correo_ElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        private AppDigitalCv.Business.ServiceClient.EnumTipoUsuario TipoUsuarioField;
        
        private AppDigitalCv.Business.ServiceClient.EnumTipoPersonal TipoPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniversidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppDigitalCv.Business.ServiceClient.EnumCodigosError CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool AccesoUsuario {
            get {
                return this.AccesoUsuarioField;
            }
            set {
                if ((this.AccesoUsuarioField.Equals(value) != true)) {
                    this.AccesoUsuarioField = value;
                    this.RaisePropertyChanged("AccesoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre_usuario {
            get {
                return this.Nombre_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_usuarioField, value) != true)) {
                    this.Nombre_usuarioField = value;
                    this.RaisePropertyChanged("Nombre_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Correo_Electronico {
            get {
                return this.Correo_ElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.Correo_ElectronicoField, value) != true)) {
                    this.Correo_ElectronicoField = value;
                    this.RaisePropertyChanged("Correo_Electronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public AppDigitalCv.Business.ServiceClient.EnumTipoUsuario TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((this.TipoUsuarioField.Equals(value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public AppDigitalCv.Business.ServiceClient.EnumTipoPersonal TipoPersonal {
            get {
                return this.TipoPersonalField;
            }
            set {
                if ((this.TipoPersonalField.Equals(value) != true)) {
                    this.TipoPersonalField = value;
                    this.RaisePropertyChanged("TipoPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Universidad {
            get {
                return this.UniversidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UniversidadField, value) != true)) {
                    this.UniversidadField = value;
                    this.RaisePropertyChanged("Universidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumCodigosError", Namespace="http://tempuri.org/")]
    public enum EnumCodigosError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        correcto = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorConexion = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        errorCatch = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        errorAutentificacion = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        errorSeguridad = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumTipoUsuario", Namespace="http://tempuri.org/")]
    public enum EnumTipoUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Usuario_Interno = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Usuario_Universidades_Rectores = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumTipoPersonal", Namespace="http://tempuri.org/")]
    public enum EnumTipoPersonal : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Docente = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrativo = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageAlumno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MessageAlumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private AppDigitalCv.Business.ServiceClient.EnumCodigosError CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private bool AccesoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatriculaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuatrimestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAlumnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppDigitalCv.Business.ServiceClient.EnumCodigosError CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool AccesoUsuario {
            get {
                return this.AccesoUsuarioField;
            }
            set {
                if ((this.AccesoUsuarioField.Equals(value) != true)) {
                    this.AccesoUsuarioField = value;
                    this.RaisePropertyChanged("AccesoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string APaterno {
            get {
                return this.APaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.APaternoField, value) != true)) {
                    this.APaternoField = value;
                    this.RaisePropertyChanged("APaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AMaterno {
            get {
                return this.AMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.AMaternoField, value) != true)) {
                    this.AMaternoField = value;
                    this.RaisePropertyChanged("AMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Matricula {
            get {
                return this.MatriculaField;
            }
            set {
                if ((object.ReferenceEquals(this.MatriculaField, value) != true)) {
                    this.MatriculaField = value;
                    this.RaisePropertyChanged("Matricula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Carrera {
            get {
                return this.CarreraField;
            }
            set {
                if ((object.ReferenceEquals(this.CarreraField, value) != true)) {
                    this.CarreraField = value;
                    this.RaisePropertyChanged("Carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Cuatrimestre {
            get {
                return this.CuatrimestreField;
            }
            set {
                if ((object.ReferenceEquals(this.CuatrimestreField, value) != true)) {
                    this.CuatrimestreField = value;
                    this.RaisePropertyChanged("Cuatrimestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string IdAlumno {
            get {
                return this.IdAlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAlumnoField, value) != true)) {
                    this.IdAlumnoField = value;
                    this.RaisePropertyChanged("IdAlumno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHorarios", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MessageHorarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private AppDigitalCv.Business.ServiceClient.EnumCodigosError CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppDigitalCv.Business.ServiceClient.Horario[] ArrHorarioField;
        
        private bool AccesoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public AppDigitalCv.Business.ServiceClient.EnumCodigosError CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AppDigitalCv.Business.ServiceClient.Horario[] ArrHorario {
            get {
                return this.ArrHorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ArrHorarioField, value) != true)) {
                    this.ArrHorarioField = value;
                    this.RaisePropertyChanged("ArrHorario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool AccesoUsuario {
            get {
                return this.AccesoUsuarioField;
            }
            set {
                if ((this.AccesoUsuarioField.Equals(value) != true)) {
                    this.AccesoUsuarioField = value;
                    this.RaisePropertyChanged("AccesoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Horario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Horario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsignaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Asignatura {
            get {
                return this.AsignaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.AsignaturaField, value) != true)) {
                    this.AsignaturaField = value;
                    this.RaisePropertyChanged("Asignatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dia {
            get {
                return this.DiaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaField, value) != true)) {
                    this.DiaField = value;
                    this.RaisePropertyChanged("Dia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClient.wsusuariosSoap")]
    public interface wsusuariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _seguridad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaUsuarios2", ReplyAction="*")]
        AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Response ConsultaUsuarios2(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaUsuarios2", ReplyAction="*")]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Response> ConsultaUsuarios2Async(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _seguridad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaUsuarios3", ReplyAction="*")]
        AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Response ConsultaUsuarios3(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaUsuarios3", ReplyAction="*")]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Response> ConsultaUsuarios3Async(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _seguridad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaUsuarios", ReplyAction="*")]
        AppDigitalCv.Business.ServiceClient.ConsultaUsuariosResponse ConsultaUsuarios(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuariosResponse> ConsultaUsuariosAsync(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _seguridad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaUsuariosAlumno", ReplyAction="*")]
        AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoResponse ConsultaUsuariosAlumno(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaUsuariosAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoResponse> ConsultaUsuariosAlumnoAsync(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _seguridad del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarHorarioProfesor", ReplyAction="*")]
        AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorResponse ConsultarHorarioProfesor(AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarHorarioProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorResponse> ConsultarHorarioProfesorAsync(AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaUsuarios2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaUsuarios2", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2RequestBody Body;
        
        public ConsultaUsuarios2Request() {
        }
        
        public ConsultaUsuarios2Request(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuarios2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.Seguridad _seguridad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AppDigitalCv.Business.ServiceClient.Usuario _usuario;
        
        public ConsultaUsuarios2RequestBody() {
        }
        
        public ConsultaUsuarios2RequestBody(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            this._seguridad = _seguridad;
            this._usuario = _usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaUsuarios2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaUsuarios2Response", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2ResponseBody Body;
        
        public ConsultaUsuarios2Response() {
        }
        
        public ConsultaUsuarios2Response(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuarios2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.Message ConsultaUsuarios2Result;
        
        public ConsultaUsuarios2ResponseBody() {
        }
        
        public ConsultaUsuarios2ResponseBody(AppDigitalCv.Business.ServiceClient.Message ConsultaUsuarios2Result) {
            this.ConsultaUsuarios2Result = ConsultaUsuarios2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaUsuarios3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaUsuarios3", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3RequestBody Body;
        
        public ConsultaUsuarios3Request() {
        }
        
        public ConsultaUsuarios3Request(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuarios3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.Seguridad _seguridad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AppDigitalCv.Business.ServiceClient.Usuario _usuario;
        
        public ConsultaUsuarios3RequestBody() {
        }
        
        public ConsultaUsuarios3RequestBody(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            this._seguridad = _seguridad;
            this._usuario = _usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaUsuarios3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaUsuarios3Response", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3ResponseBody Body;
        
        public ConsultaUsuarios3Response() {
        }
        
        public ConsultaUsuarios3Response(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuarios3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.Message ConsultaUsuarios3Result;
        
        public ConsultaUsuarios3ResponseBody() {
        }
        
        public ConsultaUsuarios3ResponseBody(AppDigitalCv.Business.ServiceClient.Message ConsultaUsuarios3Result) {
            this.ConsultaUsuarios3Result = ConsultaUsuarios3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequestBody Body;
        
        public ConsultaUsuariosRequest() {
        }
        
        public ConsultaUsuariosRequest(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuariosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.Seguridad _seguridad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AppDigitalCv.Business.ServiceClient.Usuario _usuario;
        
        public ConsultaUsuariosRequestBody() {
        }
        
        public ConsultaUsuariosRequestBody(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            this._seguridad = _seguridad;
            this._usuario = _usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultaUsuariosResponseBody Body;
        
        public ConsultaUsuariosResponse() {
        }
        
        public ConsultaUsuariosResponse(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.Message ConsultaUsuariosResult;
        
        public ConsultaUsuariosResponseBody() {
        }
        
        public ConsultaUsuariosResponseBody(AppDigitalCv.Business.ServiceClient.Message ConsultaUsuariosResult) {
            this.ConsultaUsuariosResult = ConsultaUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaUsuariosAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaUsuariosAlumno", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequestBody Body;
        
        public ConsultaUsuariosAlumnoRequest() {
        }
        
        public ConsultaUsuariosAlumnoRequest(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuariosAlumnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.Seguridad _seguridad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AppDigitalCv.Business.ServiceClient.Usuario _usuario;
        
        public ConsultaUsuariosAlumnoRequestBody() {
        }
        
        public ConsultaUsuariosAlumnoRequestBody(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            this._seguridad = _seguridad;
            this._usuario = _usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaUsuariosAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaUsuariosAlumnoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoResponseBody Body;
        
        public ConsultaUsuariosAlumnoResponse() {
        }
        
        public ConsultaUsuariosAlumnoResponse(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaUsuariosAlumnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.MessageAlumno ConsultaUsuariosAlumnoResult;
        
        public ConsultaUsuariosAlumnoResponseBody() {
        }
        
        public ConsultaUsuariosAlumnoResponseBody(AppDigitalCv.Business.ServiceClient.MessageAlumno ConsultaUsuariosAlumnoResult) {
            this.ConsultaUsuariosAlumnoResult = ConsultaUsuariosAlumnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarHorarioProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarHorarioProfesor", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequestBody Body;
        
        public ConsultarHorarioProfesorRequest() {
        }
        
        public ConsultarHorarioProfesorRequest(AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarHorarioProfesorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.Seguridad _seguridad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AppDigitalCv.Business.ServiceClient.Usuario _usuario;
        
        public ConsultarHorarioProfesorRequestBody() {
        }
        
        public ConsultarHorarioProfesorRequestBody(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            this._seguridad = _seguridad;
            this._usuario = _usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarHorarioProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarHorarioProfesorResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorResponseBody Body;
        
        public ConsultarHorarioProfesorResponse() {
        }
        
        public ConsultarHorarioProfesorResponse(AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarHorarioProfesorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppDigitalCv.Business.ServiceClient.MessageHorarios ConsultarHorarioProfesorResult;
        
        public ConsultarHorarioProfesorResponseBody() {
        }
        
        public ConsultarHorarioProfesorResponseBody(AppDigitalCv.Business.ServiceClient.MessageHorarios ConsultarHorarioProfesorResult) {
            this.ConsultarHorarioProfesorResult = ConsultarHorarioProfesorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsusuariosSoapChannel : AppDigitalCv.Business.ServiceClient.wsusuariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsusuariosSoapClient : System.ServiceModel.ClientBase<AppDigitalCv.Business.ServiceClient.wsusuariosSoap>, AppDigitalCv.Business.ServiceClient.wsusuariosSoap {
        
        public wsusuariosSoapClient() {
        }
        
        public wsusuariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsusuariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsusuariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsusuariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Response AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultaUsuarios2(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Request request) {
            return base.Channel.ConsultaUsuarios2(request);
        }
        
        public AppDigitalCv.Business.ServiceClient.Message ConsultaUsuarios2(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Request inValue = new AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Request();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2RequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Response retVal = ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultaUsuarios2(inValue);
            return retVal.Body.ConsultaUsuarios2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Response> AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultaUsuarios2Async(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Request request) {
            return base.Channel.ConsultaUsuarios2Async(request);
        }
        
        public System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Response> ConsultaUsuarios2Async(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Request inValue = new AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2Request();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultaUsuarios2RequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            return ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultaUsuarios2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Response AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultaUsuarios3(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Request request) {
            return base.Channel.ConsultaUsuarios3(request);
        }
        
        public AppDigitalCv.Business.ServiceClient.Message ConsultaUsuarios3(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Request inValue = new AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Request();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3RequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Response retVal = ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultaUsuarios3(inValue);
            return retVal.Body.ConsultaUsuarios3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Response> AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultaUsuarios3Async(AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Request request) {
            return base.Channel.ConsultaUsuarios3Async(request);
        }
        
        public System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Response> ConsultaUsuarios3Async(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Request inValue = new AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3Request();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultaUsuarios3RequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            return ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultaUsuarios3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppDigitalCv.Business.ServiceClient.ConsultaUsuariosResponse AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultaUsuarios(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequest request) {
            return base.Channel.ConsultaUsuarios(request);
        }
        
        public AppDigitalCv.Business.ServiceClient.Message ConsultaUsuarios(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequest inValue = new AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequest();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            AppDigitalCv.Business.ServiceClient.ConsultaUsuariosResponse retVal = ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultaUsuarios(inValue);
            return retVal.Body.ConsultaUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuariosResponse> AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultaUsuariosAsync(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequest request) {
            return base.Channel.ConsultaUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuariosResponse> ConsultaUsuariosAsync(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequest inValue = new AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequest();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultaUsuariosRequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            return ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultaUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoResponse AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultaUsuariosAlumno(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequest request) {
            return base.Channel.ConsultaUsuariosAlumno(request);
        }
        
        public AppDigitalCv.Business.ServiceClient.MessageAlumno ConsultaUsuariosAlumno(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequest inValue = new AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequest();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoResponse retVal = ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultaUsuariosAlumno(inValue);
            return retVal.Body.ConsultaUsuariosAlumnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoResponse> AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultaUsuariosAlumnoAsync(AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequest request) {
            return base.Channel.ConsultaUsuariosAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoResponse> ConsultaUsuariosAlumnoAsync(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequest inValue = new AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequest();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultaUsuariosAlumnoRequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            return ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultaUsuariosAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorResponse AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultarHorarioProfesor(AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequest request) {
            return base.Channel.ConsultarHorarioProfesor(request);
        }
        
        public AppDigitalCv.Business.ServiceClient.MessageHorarios ConsultarHorarioProfesor(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequest inValue = new AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequest();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorResponse retVal = ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultarHorarioProfesor(inValue);
            return retVal.Body.ConsultarHorarioProfesorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorResponse> AppDigitalCv.Business.ServiceClient.wsusuariosSoap.ConsultarHorarioProfesorAsync(AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequest request) {
            return base.Channel.ConsultarHorarioProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorResponse> ConsultarHorarioProfesorAsync(AppDigitalCv.Business.ServiceClient.Seguridad _seguridad, AppDigitalCv.Business.ServiceClient.Usuario _usuario) {
            AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequest inValue = new AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequest();
            inValue.Body = new AppDigitalCv.Business.ServiceClient.ConsultarHorarioProfesorRequestBody();
            inValue.Body._seguridad = _seguridad;
            inValue.Body._usuario = _usuario;
            return ((AppDigitalCv.Business.ServiceClient.wsusuariosSoap)(this)).ConsultarHorarioProfesorAsync(inValue);
        }
    }
}
